### ISSUE TITLE
build failing?

### ISSUE THREAD

**Issue by mnfienen** [CUAHSI/cuahsi-stacks#13]
@Castronova - if you get a chance can you try building https://github.com/CUAHSI/cuahsi-stacks/blob/master/singleuser/python3-modflow6/Dockerfile ? For some reason, it's not working on my end but it very well could be an IT security issue....

**Comment by Castronova** [comment]
Absolutely. I'll test this out today.

**Comment by mnfienen** [comment]
sweet - thanks! LMK how it goes.
